# Uncomment the next line to define a global platform for your project
 platform :ios, ’10.0’

target 'Tanoura' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tanoura

	pod 'SlideMenuControllerSwift'
	pod 'DynamicButton', '~> 3.1.0'
	pod 'SwiftyTimer'
	pod 'SwiftyUserDefaults'
	pod 'SwifterSwift' , :tag =>'v1.6.2’ , :git => 'https://github.com/omaralbeik/SwifterSwift.git'
	pod 'SnapKit'
	pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
	pod 'ActionKit', :branch => 'swift3' ,:git => 'https://github.com/ActionKit/ActionKit.git'

  target 'TanouraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TanouraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
